version: '3'
services:
  php-apache:
    image: php:7.1.26-apache
    ports:
      - 8079:80
    volumes:
      - ./DocumentRoot:/var/www/html:z
    links:
      - 'mysql'

  mysql:
    image: mysql:8.0.14
    volumes:
      - mysql:/var/lib/mysql
    environment:
      TZ: "America/Chicago"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpassword'
      MYSQL_DATABASE: 'testdb'

volumes:
  mysql:
